### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by DominiqueMakowski** [Sussex-Psychology-Software-Team/DoggoNogo#3]
I just made a test with the following URL:

https://sussex-psychology-software-team.github.io/DoggoNogo/?datapipe=Vqb57uxj5LaN&p=dupa&s=DoggoNogoValidation&l1n=30

to send this to this repo:
![image](https://github.com/user-attachments/assets/cc4e2f96-78b3-480a-810e-80858b6b3e83)

But I haven't received the data. Might be a bug in the sending?

**Comment by Max-Lovell** [comment]
Turn off the data validation, it's filtering anything out without a trial_type field.

**Comment by DominiqueMakowski** [comment]
Assuming the `participant` URLvar is filled, can we save the filename as `DoggoNogo_{participant}_{randomStrings}` and `DoggoNogo_{randomStrings}` if not 

It will make it easier to select the according data files in the future if we need

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/user-attachments/assets/b6ddad48-9f5b-46ae-bdb9-3d4c52cd4e0b)

to clarify, `start` is the full start date, and `trialsStart` is the start of lvl1? And so  `trialsStart`-`startDate` is the duration of the introduction?
 
If so, maybe to rename to `startL1` and `endL1`(as in the future we might have `startL2` etc)

**Comment by DominiqueMakowski** [comment]
Also, isn't it weird that `userAgentString` prints *all* browsers? Like for in my example it's `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0"`

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/user-attachments/assets/8ab354e4-59cc-4438-a98d-b0e66d3bcb10)

- [ ] Finally, thinking of resilience for future, can we rename the sub-json dict currently named `trials` to s something like `l1` or `level1` so that in the future we can have separate containers for the trials of other levels?

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/user-attachments/assets/c0f9e3e5-1c9f-41bd-a806-65e20ccaeb29)

- [ ] And *finally* 😅, can we *not* save the dimensions & position as a subobject? I.e., have instead `screenSize_width` and height. And like `bonePosition_x` and `bonePosition_y` 

It's much easier to have everything at the same level to easily put it in dataframe format

**Comment by Max-Lovell** [comment]
screenSize_width is surely an ultimate naming sin - do you want the names camel case or snake_case? Looks like camel is more typical generally but underscores more typical in python: https://stackoverflow.com/questions/5543490/json-naming-convention-snake-case-camelcase-or-pascalcase

**Comment by DominiqueMakowski** [comment]
WAIT haha, I think we forgot to save the RT ^^ that's rather important

**Comment by Max-Lovell** [comment]
oops - should be fixed UwU. Screen size is recorded on early trials now, not canvas but not sure what the use would be as there's no bone position yet.

**Comment by DominiqueMakowski** [comment]
Just tried it again now, but the data seems to be the same (i.e., no `responseTime` and screen size sill 0 for early trials. Maybe it didn't update correctly?

![image](https://github.com/user-attachments/assets/71c02536-ced1-417c-b4a6-3223695e42e3)

**Comment by Max-Lovell** [comment]
Oops I see - c# can't serialise a nullable field apparently - which happens as I wanted rt to be null on a missed trial. Making that happen is a massive pain in c#. We have 3 options for how rt can be saved for a missed trial:
1) save the rt as is - obviously there is no reaction to time, but there is still an 'rt' (i.e. the time recorded by the timer when the trial was ended, which is basically equal to the maxRT).
2) Store all rts as a string and save 'null' as a string too, which can be converted to numeric at analysis
3) Use a code for the missed rt in the correct data type as e.g. -999

lmk which you prefer. I'd opt for going with option 1 and letting people handle it themselves.

**Comment by Max-Lovell** [comment]
Also for screen size I just tested and it looks fine in my data: https://osf.io/c7gwv

**Comment by DominiqueMakowski** [comment]
for RT, yeah 1 is good, cheers

**Comment by DominiqueMakowski** [comment]
I dont like codes like -999 and i don't particularly saving it as a string either it looks hacky so 1 is the best

**Comment by Max-Lovell** [comment]
okay done, build in progress

**Comment by DominiqueMakowski** [comment]
Cheers, I think it all works! I'll run a couple of pilots and will confirm that it all works as expected and then we can push a release
